import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./provider";

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${plusJakartaSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Providers>{children}</Providers>
        </main>
        <Toaster
          duration={Infinity}
          closeButton={true}
          toastOptions={{
            unstyled: true,

            classNames: {
              toast:
                "group toast border-l-4 border bg-background border-border flex gap-2 p-5 min-w-50 rounded-mid text-foreground",

              title: "text-base font-medium",
              description: "text-sm text-muted-foreground",

              success: "border-l-success ",

              error: "border-l-destructive",

              icon: "group-[.success]:!text-success group-[.error]:!text-destructive",
            },
          }}
        />
      </body>
    </html>
  );
}
